### ISSUE TITLE
Add basic shape models

### ISSUE THREAD

**Issue by bpe2** [usnistgov/NetSimulyzer#25]
Since we cannot capture every use case with models representing something specific like a cellphone, add the following 3D shapes as models:

* Cube
* Sphere
* Square Pyramid
* Diamond

Each of these should use a configurable base material, so their colors may be set by the `BaseColor` attribute and have all points within roughly 1 unit of the origin.

Are there any other basic shapes we'd like to have?

**Comment by bpe2** [comment]
Here's a screenshot of the models from above using each color from the palette

![Screenshot from 2021-04-14 13-27-11](https://user-images.githubusercontent.com/54951512/114753289-4ad8b900-9d25-11eb-805e-2a314c54e71e.png)

**Comment by richardrouil** [comment]
That looks nice. How will you have the user specify the shape instead of a model file? Will you check if the string has an extension or would you have a different method to call, or something else? 

Just to confirm too. Will you be able to change the color throughout the simulation? That would be a neat feature to be able to  provide visual cues about the state of node.

**Comment by bpe2** [comment]
Currently, you specify a shape the same way you specify a model. There will be constants for these just like the other models.

I have an issue in for changing the base/highlight colors during the simulation [\#109 on GitLab](https://gitlab.nist.gov/gitlab/wnd-publicsafety/visualizer/NetSimulyzer/-/issues/109), but I haven't quite got to that yet. That shouldn't be too challenging to do though.
